const GET_REQUEST = "GET_REQUEST";

const GET_SUCCESS = "GET_SUCCESS";
const GET_FAIL = "GET_FAIL";

const USER_SIGNIN = "USER_SIGNIN";
const USER_LOGOUT = "USER_LOGOUT";

const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export {
  GET_REQUEST,
  GET_SUCCESS,
  GET_FAIL,
  USER_SIGNIN,
  USER_LOGOUT,
  ADD_TO_CART,
  REMOVE_FROM_CART,
}